Repository andersevenrud/nordic.nvim, pull requests merged in 2021-12, with the labels that each got.

#51 Add contribution guide and examples
  CONTRIBUTING.md
  README.md
  lua/nordic/colors/example.lua
  lua/nordic/init.lua
Labels: documentation

#54 Add `CopilotSuggestion` to colorscheme
  lua/nordic/colors/copilot.lua
  lua/nordic/colors/init.lua
Labels: enhancement

#55 Improve contrast and intensity of lightspeed.nvim colors
  lua/nordic/colors/lightspeed.lua
Labels: enhancement

#57 Add support for Packer
  lua/nordic/colors/init.lua
  lua/nordic/colors/packer.lua
Labels: enhancement

#58 ci: use conventional commit specification
  .github/workflows/lint.yml
  CONTRIBUTING.md
Labels: documentation, enhancement
